version: "3.7"
name: tell-us-who-you-employ-prod
services:
  # tell-us-who-you-employ app

  app:
    image: "tell-us-who-you-employ"
    # command: ["tail", "-f", "/dev/null"]
    pull_policy: build
    init: true
    depends_on:
      - postgres
    build:
      context: .
      target: ${RAILS_ENV:-production}
      args:
        NODE_ENV: ${NODE_ENV:-production}
        RAILS_ENV: ${RAILS_ENV:-production}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      RAILS_ENV: ${RAILS_ENV:-production}
      RACK_ENV: ${RACK_ENV:-production}
      APP_ENV: ${APP_ENV:-production}
      DATABASE_URL: ${DATABASE_URL:-postgresql://tell-us-who-you-employ:password@postgres:5432/tell-us-who-you-employ?}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES:-true}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - internal_network

  # proxy (because ssl)
  proxy:
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/usr/src/app
      - ./environment/proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/tell-us.local.crt:/etc/ssl/certificate.crt
      - ./certs/tell-us.local.key:/etc/ssl/certificate.key
      # - ./public:/usr/src/app/public
    depends_on:
      - app
    networks:
      - external_network
      - internal_network

  # Databases

  postgres:
    image: postgres:13.7-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tell-us-who-you-employ}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-tell-us-who-you-employ_production}
    ports:
      - 5434:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  postgres-volume:

networks:
  external_network:
  internal_network:
    internal: true
