default: &default
  adapter: postgresql
  encoding: unicode
  port: 5433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch("RAILS_TIMEOUT") { 5000 } %>

development:
  <<: *default
  database: tell-us-who-you-employ_development

test:
  <<: *default
  database: tell-us-who-you-employ_test
  url: postgresql://localhost/tell-us-who-you-employ_test
  username: postgres
  password: postgres


production:
  <<: *default
  database: tell-us-who-you-employ_production
  username: tell-us-who-you-employ
  password: <%= ENV['TELL-US-WHO-YOU-EMPLOY_DATABASE_PASSWORD'] %>
