default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch("RAILS_TIMEOUT") { 5000 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "postgresql://tell-us-who-you-employ:password@localhost/tell-us-who-you-employ?" }.gsub('?', '_development?') %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "postgresql://tell-us-who-you-employ:password@localhost/tell-us-who-you-employ?" }.gsub('?', '_test?') %>

# staging:
#   <<: *default
#   url: <%= ENV.fetch("DATABASE_URL"){ "postgresql://localhost/tell-us-who-you-employ?" }.gsub('?', '_staging?') %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "postgresql://localhost/tell-us-who-you-employ?" }.gsub('?', '_production?') %>
